name: trigger-replace-links

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: jrobrien91/suny-oswego-workshop-2024
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "ProjectPythia/cookbook-template"
          replace: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
          regex: false
          exclude: ".github/workflows/trigger-replace-links.yaml"

      - name: https://github.com/jrobrien91/suny-oswego-workshop-2024.git
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "475509405"
          replace: "${{ github.repository_id}}"
          regex: false
          exclude: ".github/workflows/trigger-replace-links.yaml"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
